"""Product scaffolding for self-hosted MCP Nexus installs."""

from __future__ import annotations

import getpass
import shlex
import sys
from pathlib import Path

from mcp_nexus.config import Settings


def _env_value(value: object) -> str:
    if value is None:
        return ""
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (list, tuple)):
        return ",".join(str(item) for item in value if str(item))
    return str(value)


def _env_line(key: str, value: object) -> str:
    return f"{key}={_env_value(value)}"


def render_env_file(settings: Settings) -> str:
    """Render a runnable .env file from the current settings."""
    lines = [
        "# MCP Nexus Server Configuration",
        "# Generated by `mcp-nexus init`.",
        "",
        "# SSH Connection",
        _env_line("NEXUS_SSH_HOST", settings.ssh_host),
        _env_line("NEXUS_SSH_PORT", settings.ssh_port),
        _env_line("NEXUS_SSH_USER", settings.ssh_user),
        _env_line("NEXUS_SSH_KEY_PATH", settings.ssh_key_path),
        _env_line("NEXUS_SSH_PASSWORD", settings.ssh_password),
        _env_line("NEXUS_SSH_POOL_SIZE", settings.ssh_pool_size),
        "",
        "# Public OAuth / ChatGPT Connect",
        _env_line("NEXUS_PUBLIC_BASE_URL", settings.public_base_url),
        _env_line("NEXUS_OAUTH_ENABLED", settings.oauth_enabled),
        _env_line("NEXUS_OAUTH_ISSUER", settings.oauth_issuer),
        _env_line("NEXUS_OAUTH_CLIENT_ID", settings.oauth_client_id),
        _env_line("NEXUS_OAUTH_CLIENT_SECRET", settings.oauth_client_secret),
        _env_line("NEXUS_OAUTH_CLIENT_REDIRECT_URIS", settings.oauth_client_redirect_uris),
        _env_line("NEXUS_OAUTH_SCOPES", settings.oauth_scopes),
        _env_line("NEXUS_OAUTH_DEFAULT_SCOPES", settings.oauth_default_scopes),
        _env_line("NEXUS_OAUTH_TOKEN_TTL_SECONDS", settings.oauth_token_ttl_seconds),
        _env_line("NEXUS_OAUTH_REFRESH_TTL_SECONDS", settings.oauth_refresh_ttl_seconds),
        _env_line("NEXUS_OAUTH_AUTHORIZATION_CODE_TTL_SECONDS", settings.oauth_authorization_code_ttl_seconds),
        _env_line("NEXUS_OAUTH_CONSENT_PATH", settings.oauth_consent_path),
        _env_line("NEXUS_STATE_ROOT", settings.state_root),
        _env_line("NEXUS_STATE_ENCRYPTION_KEY", settings.state_encryption_key),
        "",
        "# Server",
        _env_line("NEXUS_HOST", settings.host),
        _env_line("NEXUS_PORT", settings.port),
        _env_line("NEXUS_MCP_PATH", settings.mcp_path),
        _env_line("NEXUS_MCP_PATH_ALIASES", settings.mcp_path_aliases),
        _env_line("NEXUS_LOG_LEVEL", settings.log_level),
        _env_line("NEXUS_DEFAULT_CWD", settings.default_cwd),
        _env_line("NEXUS_COMMAND_TIMEOUT", settings.default_command_timeout),
        _env_line("NEXUS_OUTPUT_LIMIT_BYTES", settings.output_limit_bytes),
        _env_line("NEXUS_ERROR_LIMIT_BYTES", settings.error_limit_bytes),
        _env_line("NEXUS_OUTPUT_PREVIEW_BYTES", settings.output_preview_bytes),
        _env_line("NEXUS_ERROR_PREVIEW_BYTES", settings.error_preview_bytes),
        _env_line("NEXUS_ARTIFACT_ROOT", settings.artifact_root),
        _env_line("NEXUS_TOOL_ALIAS_BASE", settings.tool_alias_base),
        _env_line("NEXUS_FORWARDED_HEADERS", settings.forwarded_headers),
        _env_line("NEXUS_RUNNING_IN_CONTAINER", settings.runtime_container),
        _env_line("NEXUS_HOST_BRIDGE_ADDRESS", settings.host_bridge_address),
        _env_line("NEXUS_ALLOW_CONTAINER_LOCALHOST_EXEC", settings.allow_container_localhost_exec),
        "",
        "# Intelligence",
        _env_line("NEXUS_INTELLIGENCE", settings.intelligence_enabled),
        _env_line("NEXUS_DATA_DIR", settings.data_dir),
        _env_line("NEXUS_AUDIT_LOG_FILE", settings.audit_log_file),
        "",
        "# Runtime & Release Paths (evaluated on the target host)",
        _env_line("NEXUS_SANDBOX_ROOT", settings.sandbox_root),
        _env_line("NEXUS_JOB_ROOT", settings.job_root),
        _env_line("NEXUS_RELEASE_ROOT", settings.release_root),
        _env_line("NEXUS_CURRENT_RELEASE_LINK", settings.current_release_link),
        "",
        "# Database (optional)",
        (
            '# Example: '
            'NEXUS_DB_PROFILES_JSON={"warehouse":{"host":"localhost","port":5432,"database":"analytics",'
            '"user":"readonly","password":"change-me","sslmode":"require"}}'
        ),
        _env_line("NEXUS_DB_PROFILES_JSON", settings.db_profiles_json),
        _env_line("NEXUS_DB_DEFAULT_PROFILE", settings.db_default_profile),
        _env_line("NEXUS_DB_HOST", settings.db_host),
        _env_line("NEXUS_DB_DSN", settings.db_dsn_value),
        _env_line("NEXUS_DB_PORT", settings.db_port),
        _env_line("NEXUS_DB_NAME", settings.db_name),
        _env_line("NEXUS_DB_USER", settings.db_user),
        _env_line("NEXUS_DB_PASSWORD", settings.db_password),
        _env_line("NEXUS_DB_SSLMODE", settings.db_sslmode),
        "",
        "# Rate Limiting",
        _env_line("NEXUS_RATE_LIMIT_RPM", settings.rate_limit_rpm),
        _env_line("NEXUS_RATE_LIMIT_BURST", settings.rate_limit_burst),
        "",
        "# Watchdog",
        _env_line("NEXUS_WATCHDOG_SERVICES", settings.watchdog_services),
        _env_line("NEXUS_WATCHDOG_INTERVAL", settings.watchdog_interval),
        _env_line("NEXUS_MAX_RESTART_ATTEMPTS", settings.max_restart_attempts),
        _env_line("NEXUS_RESTART_COOLDOWN", settings.restart_cooldown),
        "",
    ]
    return "\n".join(lines)


def default_service_user() -> str:
    return getpass.getuser()


def default_exec_command(*, port: int, python_executable: str | None = None) -> str:
    interpreter = python_executable or sys.executable
    return f"{shlex.quote(interpreter)} -m mcp_nexus serve --host 127.0.0.1 --port {port}"


def render_systemd_unit(
    *,
    service_name: str,
    working_directory: str,
    env_file: str,
    exec_command: str,
    service_user: str = "",
) -> str:
    """Render a portable systemd unit for the installed package."""
    user_line = f"User={service_user}\n" if service_user else ""
    return (
        "[Unit]\n"
        f"Description={service_name}\n"
        "After=network.target\n"
        "Wants=network-online.target\n"
        "StartLimitBurst=10\n"
        "StartLimitIntervalSec=120\n"
        "\n"
        "[Service]\n"
        "Type=simple\n"
        f"{user_line}"
        f"WorkingDirectory={working_directory}\n"
        f"EnvironmentFile={env_file}\n"
        f"ExecStart={exec_command}\n"
        "Restart=always\n"
        "RestartSec=3\n"
        "OOMScoreAdjust=-500\n"
        "LimitNOFILE=65535\n"
        "StandardOutput=journal\n"
        "StandardError=journal\n"
        "\n"
        "[Install]\n"
        "WantedBy=multi-user.target\n"
    )


def write_scaffold(
    target_dir: str | Path,
    *,
    settings: Settings,
    force: bool = False,
    include_systemd: bool = False,
    service_name: str = "mcp-nexus",
    service_user: str | None = None,
    exec_command: str | None = None,
) -> list[Path]:
    """Write product scaffold files into a target directory."""
    base_path = Path(target_dir).expanduser().resolve()
    base_path.mkdir(parents=True, exist_ok=True)

    artifacts: dict[Path, str] = {
        base_path / ".env": render_env_file(settings),
    }
    if include_systemd:
        unit_path = base_path / f"{service_name}.service"
        artifacts[unit_path] = render_systemd_unit(
            service_name=service_name,
            working_directory=str(base_path),
            env_file=str(base_path / ".env"),
            exec_command=exec_command or default_exec_command(port=settings.port),
            service_user=service_user if service_user is not None else default_service_user(),
        )

    existing = [path for path in artifacts if path.exists()]
    if existing and not force:
        names = ", ".join(path.name for path in existing)
        raise FileExistsError(f"Refusing to overwrite existing files without --force: {names}")

    for path, content in artifacts.items():
        path.write_text(content.rstrip() + "\n", encoding="utf-8")

    return sorted(artifacts)
